# Generated by Django 5.0.4 on 2024-04-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surfScrapperApp', '0002_rename_subscribers_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
