# Generated by Django 5.0.4 on 2024-04-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.CharField(max_length=200)),
                ('trackedBeaches', models.CharField(max_length=5000)),
            ],
        ),
    ]
