# Generated by Django 5.0.4 on 2024-05-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfScrapperApi', '0003_beach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beach',
            name='totalScore',
            field=models.IntegerField(default=0),
        ),
    ]
