# Generated by Django 5.0.4 on 2024-09-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surfScrapperApi', '0004_alter_beach_totalscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='beach',
            name='indexOfDay',
            field=models.IntegerField(default=0),
        ),
    ]
